# FROM nginx:latest

# COPY ./dist/ /usr/share/nginx/html

# CMD ["nginx","-g","daemon off;"]

FROM node

WORKDIR /app
COPY . /app
RUN npm install --registry=https://registry.npm.taobao.org && npm run build

# CMD ["npm", "run", "build","node","server.js"]
CMD ["node", "server.js"]